#github action

name: upload website to S3 and invalidate cloudfront cache

on:
  push:
    branches:
      - main

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: 
        uses: actions/checkout@v4

      - name:
        uses: actions/setup-node@v4
